---
# yaml-language-server: $schema=https://schema.blue-build.org/recipe-v1.json

name: monolith
description: This is my personal OS image.

base-image: ghcr.io/ublue-os/silverblue-main
image-version: 44

modules:
  - type: files
    files:
      - source: system
        destination: /

  - type: dnf
    repos:
      copr:
        - lilay/topgrade

      files:
        - https://brave-browser-rpm-release.s3.brave.com/brave-browser.repo
        - https://pkgs.tailscale.com/stable/fedora/tailscale.repo
        - https://negativo17.org/repos/fedora-steam.repo

      keys:
        - https://brave-browser-rpm-release.s3.brave.com/brave-core.asc
        - https://pkgs.tailscale.com/stable/fedora/repo.gpg
        - https://negativo17.org/repos/RPM-GPG-KEY-slaanesh

    install:
      packages:
        - nano
        - fish
        - tailscale
        - topgrade
        - steam-devices

        - repo: brave-browser
          packages:
            - brave-origin

        - repo: fedora-steam
          install-weak-deps: false
          packages:
            - steam

    remove:
      packages:
        - firefox
        - firefox-langpacks

  - type: systemd
    system:
      enabled:
        - tailscaled.service

  - type: gnome-extensions
    install:
      - AppIndicator and KStatusNotifierItem Support
      - Blur my Shell
      - Clipboard History
      - Tiling Shell

  - type: gschema-overrides
    include:
      - zz1-gnome-extensions.gschema.override

  - type: default-flatpaks
    configurations:
      - notify: true
        scope: system
        install:
          - org.gnome.Loupe
          - io.github.kolunmi.Bazaar
          - com.mattjakeman.ExtensionManager
          - com.vysp3r.ProtonPlus
          - com.github.zocker_160.SyncThingy
          - com.saivert.pwvucontrol
          - org.jellyfin.JellyfinDesktop
          - io.github.getnf.embellish
          - org.cryptomator.Cryptomator

      - scope: user

  - type: signing
